handler: ansible
version: 1.0.0

actions:
  exclude_mac_pxe: exclude_mac_pxe.yaml
  run: run.yaml

input:
    ip:
      schema: str!
      value:

    exclude_mac_pxe:
      schema: str!
      value:

tags: [resources=dnsmasq]
