- hosts: [{{ ip }}]
  sudo: yes
  tasks:
    - name: mariadb user
      mysql_user:
        name: {{ user_name }}
        password: {{ user_password }}
        priv: {{ db_name }}.*:ALL
        host: '%'
        state: present
        login_user: root
        login_password: {{ login_password }}
        login_port: {{ login_port }}
        login_host: 127.0.0.1
