handler: ansible
version: 1.0.0
actions:
  join: actions/join.yaml
input:
    join_to:
      schema: str!
      value:
    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:
