handler: puppet
puppet_module: keystone
version: 1.0.0
input:
    admin_token:
      schema: str!
      value: admin_token
    db_user:
      schema: str!
      value:
    db_password:
      schema: str!
      value:
    db_name:
      schema: str!
      value: 
    db_host:
      schema: str!
      value: 
    db_port:
      schema: int!
      value: 

    admin_port:
      schema: int!
      value: 35357
    port:
      schema: int!
      value: 5000

    module:
      schema: {name: str!, type: str, url: str, ref: str}
      value: {name: 'keystone', type: 'git', url: 'https://github.com/openstack/puppet-keystone', ref: '5.1.0'}

    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:

tags: [resource/keystone_service, resources/keystone]
