id: haproxy_config
handler: ansible
version: 1.0.0
input:
    ip:
      schema: str!
      value:
    config_dir:
      schema: {src: str!, dst: str!}
      value: {src: /etc/solar/haproxy, dst: /etc/haproxy}
    config:
      schema: [{backends: [{server: str!, port: int!}], listen_port: int!, protocol: str!, name: str!}]
      value: []
    ssh_user:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:

tags: [resources/haproxy, resource/haproxy_config]
