handler: puppet
input:
  ip:
    schema: str!
    value:
  # ssh_key:
  #   schema: str!
  #   value:
  # ssh_user:
  #   schema: str!
  #   value:

  package_ensure:
    schema: str
    value: 'present'
  verbose:
    schema: bool
    value: false
  debug:
    schema: bool
    value: false
  bind_host:
    schema: str
    value: '0.0.0.0'
  bind_port:
    schema: int
    value: 9696
  core_plugin:
    schema: str
    value: 'openvswitch'
  service_plugins:
    schema: str
    value:
  auth_strategy:
    schema: str
    value: 'keystone'
  base_mac:
    schema: str
    value: 'fa:16:3e:00:00:00'
  mac_generation_retries:
    schema: int
    value: 16
  dhcp_lease_duration:
    schema: int
    value: 86400
  dhcp_agents_per_network:
    schema: int
    value: 1
  network_device_mtu:
    schema: str
    value:
  dhcp_agent_notification:
    schema: bool
    value: true
  allow_bulk:
    schema: bool
    value: true
  allow_pagination:
    schema: bool
    value: false
  allow_sorting:
    schema: bool
    value: false
  allow_overlapping_ips:
    schema: bool
    value: false
  api_extensions_path:
    schema: str
    value:
  root_helper:
    schema: str
    value: 'sudo neutron-rootwrap /etc/neutron/rootwrap.conf'
  report_interval:
    schema: int
    value: 30
  control_exchange:
    schema: str
    value: 'neutron'
  rpc_backend:
    schema: str
    value: 'neutron.openstack.common.rpc.impl_kombu'
  rabbit_password:
    schema: str!
    value:
  rabbit_host:
    schema: str
    value: 'localhost'
  rabbit_hosts:
    schema: bool
    value: false
  rabbit_port:
    schema: int
    value: 5672
  rabbit_user:
    schema: str
    value: 'guest'
  rabbit_virtual_host:
    schema: str
    value: '/'
  rabbit_use_ssl:
    schema: bool
    value: false
  kombu_ssl_ca_certs:
    schema: str
    value:
  kombu_ssl_certfile:
    schema: str
    value:
  kombu_ssl_keyfile:
    schema: str
    value:
  kombu_ssl_version:
    schema: str
    value: 'TLSv1'
  kombu_reconnect_delay:
    schema: str
    value: '1.0'
  qpid_hostname:
    schema: str
    value: 'localhost'
  qpid_port:
    schema: int
    value: 5672
  qpid_username:
    schema: str
    value: 'guest'
  qpid_password:
    schema: str!
    value: 'guest'
  qpid_heartbeat:
    schema: int
    value: 60
  qpid_protocol:
    schema: str
    value: 'tcp'
  qpid_tcp_nodelay:
    schema: bool
    value: true
  qpid_reconnect:
    schema: bool
    value: true
  qpid_reconnect_timeout:
    schema: int
    value: 0
  qpid_reconnect_limit:
    schema: int
    value: 0
  qpid_reconnect_interval_min:
    schema: int
    value: 0
  qpid_reconnect_interval_max:
    schema: int
    value: 0
  qpid_reconnect_interval:
    schema: int
    value: 0
  use_ssl:
    schema: bool
    value: false
  cert_file:
    schema: str
    value:
  key_file:
    schema: str
    value:
  ca_file:
    schema: str
    value:
  use_syslog:
    schema: bool
    value: false
  log_facility:
    schema: str
    value: 'LOG_USER'
  log_file:
    schema: str
    value:
  log_dir:
    schema: str
    value: '/var/log/neutron'

  module:
    schema: {name: str!, type: str, url: str, ref: str}
    value: {name: neutron, type: 'git', url: 'https://github.com/openstack/puppet-neutron', ref: '5.1.0'}

tags: [resource/neutron]
version: 1.0.0
