handler: puppet
input:
  ip:
    schema: str!
    value:
  # ssh_key:
  #   schema: str!
  #   value:
  # ssh_user:
  #   schema: str!
  #   value:

  auth_password:
    schema: str!
    value:
  shared_secret:
    schema: str!
    value:
  package_ensure:
    schema: str
    value: 'present'
  debug:
    schema: bool
    value: false
  auth_tenant:
    schema: str
    value: 'services'
  auth_user:
    schema: str
    value: 'neutron'
  auth_insecure:
    schema: bool
    value: false
  auth_ca_cert:
    schema: str
    value:
  auth_region:
    schema: str
    value: 'RegionOne'
  metadata_ip:
    schema: str
    value: '127.0.0.1'
  metadata_port:
    schema: int
    value: 8775
  metadata_workers:
    schema: int
    value: 1
  metadata_backlog:
    schema: int
    value: 4096
  metadata_memory_cache_ttl:
    schema: int
    value: 5

  auth_host:
    schema: str
    value: 'localhost'
  auth_port:
    schema: int
    value: 35357

  git:
    schema: {repository: str!, branch: str!}
    value: {repository: 'https://github.com/openstack/puppet-neutron', branch: '5.1.0'}

puppet_module: 'neutron'
tags: [resource/neutron, resource/neutron_agents_metadata]
version: 1.0.0
