apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: rabbitmq
    spec:
      containers:
        - image: rabbitmq:3-management
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 8080
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: default.user
             - name: RABBITMQ_DEFAULT_PASSWORD
               valueFrom:
                 configMapKeyRef:
                   name: rabbitmq-config
                   key: default.password
             - name: RABBITMQ_DEFAULT_VHOST
               valueFrom:
                 configMapKeyRef:
                   name: rabbitmq-config
                   key: default.vhost
             - name: RABBITMQ_ERLANG_COOKIE
               valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: cookie
