handler: ansible_playbook
version: 1.0.0
actions:
input:
    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:
    provides:
       schema: str
       value: infra
    roles:
      schema: [{value: str}]
      value:
        - https://github.com/stackforge/os-ansible-deployment/trunk/playbooks/roles/lxc_hosts
        - https://github.com/stackforge/os-ansible-deployment/trunk/playbooks/roles/pip_install
        - https://github.com/stackforge/os-ansible-deployment/trunk/playbooks/roles/apt_package_pinning
