id: rabbitmq_config
handler: ansible
version: 1.0.0
input:
    config_dir:
      schema: str!
      value:
    admin_name:
      schema: str!
      value:
    admin_password:
      schema: str!
      value:
    ip:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:

tags: [resources/rabbitmq, resource/rabbitmq_config]
