id: apt_repo
handler: ansible
version: 1.0.0
input:
    ip:
      schema: str!
      value:
    repo:
        schema: str!
        value:
    name:
        schema: str!
        value:
    package:
        schema: str
        value: '*'
    pin:
        schema: str
        value:
    pin_priority:
        schema: int
        value:
    validate_integrity:
        schema: bool
        value: true
