- hosts: [{{ host }}]
  sudo: yes
  tasks:
    - name: keystone service and endpoint
      keystone_service:
        token: {{admin_token}}
        name: {{endpoint_name}}
        type: {{type}}
        description: {{description}}
        publicurl: {{publicurl}}
        internalurl: {{internalurl}}
        adminurl: {{adminurl}}
        region: "RegionOne"
        state: present
        endpoint: http://{{keystone_host}}:{{keystone_admin_port}}/v2.0/
