handler: puppet
puppet_module: cinder
version: 1.0.0
input:
    package_ensure:
      schema: str
      value: 'present'
    iscsi_ip_address:
      schema: str
      value: '127.0.0.1'
    volume_driver:
      schema: str
      value: 'cinder.volume.drivers.lvm.LVMISCSIDriver'
    volume_group:
      schema: str
      value: 'cinder-volumes'
    iscsi_helper:
      schema: str
      value: 'tgtadm'

    use_iscsi_backend:
      schema: bool
      value: true

    git:
      schema: {repository: str!, branch: str!}
      value: {repository: 'https://github.com/openstack/puppet-cinder', branch: '5.1.0'}

    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:

tags: [resource/cinder_volume_service, resources/cinder_volume, resources/cinder]
