handler: puppet
input:
  ip:
    schema: str!
    value:
  # ssh_key:
  #   schema: str!
  #   value:
  # ssh_user:
  #   schema: str!
  #   value:

  port:
    schema: int!
    value: 5672
  management_port:
    schema: int! 
    value: 15672
  module:
    schema: {name: str!, type: str, url: str, ref: str}
    value: {name: 'rabbitmq', type: 'git', url: 'https://github.com/puppetlabs/puppetlabs-rabbitmq.git', ref: '5.1.0'}

tags: []
version: 1.0.0
