id: keystone_service_endpoint
handler: ansible
version: 1.0.0
input:
    keystone_host:
      schema: str!
      value:
    keystone_admin_port:
      schema: int!
      value:
    admin_token:
      schema: str!
      value:

    endpoint_name:
      schema: str!
      value:
    type:
      schema: str!
      value:
    description:
      schema: str!
      value:
    public_ip:
      schema: str!
      value:
    public_port:
      schema: int!
      value:
    publicurl:
      schema: str!
      value: http://{{public_ip}}:{{public_port}}/v2.0
    internal_ip:
      schema: str!
      value:
    internal_port:
      schema: int!
      value:
    internalurl:
      schema: str!
      value: http://{{internal_ip}}:{{internal_port}}/v2.0
    admin_ip:
      schema: str!
      value:
    admin_port:
      schema: int!
      value:
    adminurl:
      schema: str!
      value: http://{{admin_ip}}:{{admin_port}}/v2.0

    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:

tags: [resource/keystone_service_endpoint, resources/keystone]
