- hosts: [{{host}}]
  sudo: yes
  tasks:
    - rabbitmq_user: user={{user_name}}
                     password={{password}}
                     vhost={{vhost_name}}
                     configure_priv=.*
                     read_priv=.*
                     write_priv=.*
                     tags={{tags}}
                     state=present
