#! /bin/sh
### BEGIN INIT INFO
# Provides:   solar-worker
# Should-Start:   $local_fs
# Should-Stop:    $local_fs
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:  solar-worker - Solar orchestration
### END INIT INFO


PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/solar-worker
NAME=solar-worker
DESC=solar-worker
PIDFILE=/var/run/solar_worker.pid
LOGDIR=/var/log/solar
USER=vagrant:vagrant

test -x $DAEMON || exit 0
test -x $DAEMONBOOTSTRAP || exit 0

set -e

case "$1" in
  start)
  echo -n "Starting $DESC: "
  export SOLAR_CONFIG_OVERRIDE=/.solar_config_override
  touch $PIDFILE
  chown $USER $PIDFILE
  mkdir -p $LOGDIR
  chown $USER $LOGDIR
  if start-stop-daemon --start -m --background --quiet --umask 007 --pidfile $PIDFILE --chuid $USER --exec $DAEMON
  then
    echo "$NAME."
  else
    echo "failed"
  fi
  ;;
  stop)
  echo -n "Stopping $DESC: "
  if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile $PIDFILE
  then
    echo "$NAME."
  else
    echo "failed"
  fi
  rm -f $PIDFILE
  ;;

  restart|force-reload)
  ${0} stop
  ${0} start
  ;;
  *)
  echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
  exit 1
  ;;
esac

exit 0
