#! /bin/sh
### BEGIN INIT INFO
# Provides:   solar-worker
# Should-Start:   $local_fs
# Should-Stop:    $local_fs
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description:  solar-worker - Solar orchestration
### END INIT INFO

ENV=/usr/bin/env
DAEMON=solar-workerd
NAME=solar-worker
DESC=solar-worker
PIDFILE=/tmp/solar_worker.pid
LOGDIR=/var/log/solar
USER=vagrant:vagrant


set -e

export SOLAR_CONFIG_OVERRIDE=${SOLAR_CONFIG_OVERRIDE:-/.solar_config_override}

case "$1" in
  start)
  echo -n "Starting $DESC: "
  touch $PIDFILE
  chown $USER $PIDFILE
  mkdir -p $LOGDIR
  chown $USER $LOGDIR
  if start-stop-daemon --start -m --quiet --umask 007 --pidfile $PIDFILE --chuid $USER --exec $ENV $DAEMON
  then
    echo "$NAME."
  else
    echo "failed"
  fi
  ;;
  stop)
  echo -n "Stopping $DESC: "
  if start-stop-daemon --stop --retry 10 --quiet --oknodo --pidfile $PIDFILE
  then
    echo "$NAME."
  else
    echo "failed"
  fi
  rm -f $PIDFILE
  ;;

  restart|force-reload)
  ${0} stop
  ${0} start
  ;;
  *)
  echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
  exit 1
  ;;
esac

exit 0
