handler: ansible
version: 1.0.0

input:
    keystone_host:
      schema: str!
      value:
    keystone_port:
      schema: int!
      value:
    tenant:
      schema: str!
      value:
    user_name:
      schema: str!
      value:
    password:
      schema: str!
      value:
    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:
