input:
  ssh_key:
    schema: str!
    value:
  ssh_user:
    schema: str!
    value:
  ssh_port:
    schema: int!
    value: 22
  name:
    schema: str!
    value: ssh
  location_id:
    schema: str
    value:
    reverse: True
    is_own: False
  transports_id:
    schema: str
    value:
    is_emit: False
