id: mariadb_user
handler: ansible
version: 1.0.0
actions:
    run: run.yaml
    update: update.yaml
    remove: remove.yaml
input:
    user_password:
      schema: str!
      value:
    user_name:
      schema: str!
      value:

    db_name:
      schema: str!
      value:
    db_host:
      schema: str!
      value:

    login_password:
      schema: str!
      value:
    login_port:
      schema: int!
      value:
    login_user:
      schema: str!
      value:

    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:
