handler: puppet
puppet_module: l23network
version: 1.0.0
input:
    package_ensure:
      schema: str
      value: 'present'
    ensure_package:
      schema: str
      value: 'present'
    use_lnx:
      schema: bool
      value: true
    use_ovs:
      schema: bool
      value: false
    install_ovs:
      schema: bool
      value: true
    install_brtool:
      schema: bool
      value: true
    install_ethtool:
      schema: bool
      value: true
    install_bondtool:
      schema: bool
      value: true
    install_vlantool:
      schema: bool
      value: true
    ovs_modname:
      schema: str
      value: 'openvswitch'
    ovs_datapath_package_name:
      schema: str
      value: 'openvswitch-datapath-dkms'
    ovs_common_package_name:
      schema: str
      value: 'openvswitch-switch'
    network_scheme:
      schema: {
        version: str!,
        provider: str!,
        interfaces: {},
        transformations: [{}],
        endpoints: {},
        roles: {},
      }

    module:
      schema: {repository: str!, branch: str!}
      value: {name: 'l23network', type: 'git', url: 'https://github.com/xenolog/l23network', ref: '50098cfa1f0f8e8d58e6a6b77a22f1380aa5c426'}

    ip:
      schema: str!
      value:

tags: [resources/node_network]
