handler: none
version: 1.0.0
input:
    name:
      schema: str!
      value: general_haproxy
    backends:
      schema: [{server: str!, port: int!}]
    listen_port:
      schema: int!
      value: 9999
    protocol:
      schema: str!
      value: http
    # ports:
    #   schema: [int]
    #   value: []
    # servers:
    #   schema: [str]
    #   value: []

tags: [resources=haproxy]
