- hosts: [{{host}}]
  sudo: yes
  tasks:
    - shell: echo 'Managed by solar' > /etc/apt/sources.list
      when: {{ensure_other_removed}}
    - shell: apt-get update
      when: {{ensure_other_removed}}
