handler: puppet
puppet_module: glance
version: 1.0.0
input:
    package_ensure:
      schema: str
      value: 'present'
    verbose:
      schema: bool
      value: false
    debug:
      schema: bool
      value: false
    bind_host:
      schema: str
      value: '0.0.0.0'
    bind_port:
      schema: int
      value: 9191
    log_file:
      schema: str
      value: '/var/log/glance/registry.log'
    log_dir:
      schema: str
      value: '/var/log/glance'
    database_connection:
      schema: str
      value: 'sqlite:///var/lib/glance/glance.sqlite'
    database_idle_timeout:
      schema: int
      value: 3600
    auth_type:
      schema: str
      value: 'keystone'
    auth_host:
      schema: str
      value: '127.0.0.1'
    auth_port:
      schema: int
      value: 35357
    auth_admin_prefix:
      schema: str
      value:
    auth_uri:
      schema: str
      value:
    auth_protocol:
      schema: str
      value: 'http'
    keystone_tenant:
      schema: str!
      value: 'services'
    keystone_user:
      schema: str!
      value: 'glance'
    pipeline:
      schema: str
      value: 'keystone'
    use_syslog:
      schema: bool
      value: false
    log_facility:
      schema: str
      value: 'LOG_USER'
    purge_config:
      schema: bool
      value: false
    cert_file:
      schema: str
      value:
    key_file:
      schema: str
      value:
    ca_file:
      schema: str
      value:
    sync_db:
      schema: bool
      value: true
    mysql_module:
      schema: str
      value:
    sql_idle_timeout:
      schema: str
      value:
    sql_connection:
      schema: str
      value:

    git:
      schema: {repository: str!, branch: str!}
      value: {repository: 'https://github.com/openstack/puppet-glance', branch: '5.1.0'}

    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:

    db_user:
      schema: str!
      value: glance
    db_password:
      schema: str!
      value: glance
    db_name:
      schema: str!
      value: glance
    db_host:
      schema: str!
      value:
    db_port:
      schema: str!
      value:

    keystone_host:
      schema: str!
      value:
    keystone_port:
      schema: int!
      value:
    keystone_password:
      schema: str!
      value:

tags: [resource/glance_registry_service, resources/glance_registry, resource/glance]
