handler: puppet
puppet_module: nova
version: 1.0.0
actions:
    run: run.pp
    update: run.pp
input:
    ensure_package:
      schema: str
      value: 'present'
    database_connection:
      schema: str
      value:
    slave_connection:
      schema: str
      value:
    database_idle_timeout:
      schema: int
      value: 3600
    rpc_backend:
      schema: str
      value: 'rabbit'
    image_service:
      schema: str
      value: 'nova.image.glance.GlanceImageService'
    glance_api_servers:
      schema: str
      value: 'localhost:9292'
    memcached_servers:
      schema: str
      value:
    rabbit_host:
      schema: str
      value: 'localhost'
    rabbit_hosts:
      schema: str
      value:
    rabbit_password:
      schema: str!
      value: 'guest'
    rabbit_port:
      schema: int
      value: 5672
    rabbit_userid:
      schema: str
      value: 'guest'
    rabbit_virtual_host:
      schema: str
      value: '/'
    rabbit_use_ssl:
      schema: bool
      value: false
    rabbit_ha_queues:
      schema: str
      value:
    kombu_ssl_ca_certs:
      schema: str
      value:
    kombu_ssl_certfile:
      schema: str
      value:
    kombu_ssl_keyfile:
      schema: str
      value:
    kombu_ssl_version:
      schema: str
      value: 'TLSv1'
    amqp_durable_queues:
      schema: bool
      value: false
    qpid_hostname:
      schema: str
      value: 'localhost'
    qpid_port:
      schema: int
      value: 5672
    qpid_username:
      schema: str
      value: 'guest'
    qpid_password:
      schema: str!
      value: 'guest'
    qpid_sasl_mechanisms:
      schema: bool
      value: false
    qpid_heartbeat:
      schema: int
      value: 60
    qpid_protocol:
      schema: str
      value: 'tcp'
    qpid_tcp_nodelay:
      schema: bool
      value: true
    auth_strategy:
      schema: str
      value: 'keystone'
    service_down_time:
      schema: int
      value: 60
    log_dir:
      schema: str
      value: '/var/log/nova'
    state_path:
      schema: str
      value: '/var/lib/nova'
    lock_path:
      schema: str
      value: '/var/lock/nova'
    verbose:
      schema: bool
      value: false
    debug:
      schema: bool
      value: false
    periodic_interval:
      schema: int
      value: 60
    report_interval:
      schema: int
      value: 10
    rootwrap_config:
      schema: str
      value: '/etc/nova/rootwrap.conf'
    use_ssl:
      schema: bool
      value: false
    enabled_ssl_apis:
      schema: [str]
      value: ['ec2', 'metadata', 'osapi_compute']
    ca_file:
      schema: str
      value:
    cert_file:
      schema: str
      value:
    key_file:
      schema: str
      value:
    nova_user_id:
      schema: str
      value:
    nova_group_id:
      schema: str
      value:
    nova_public_key:
      schema: str
      value:
    nova_private_key:
      schema: str
      value:
    nova_shell:
      schema: str
      value: '/bin/false'
    monitoring_notifications:
      schema: bool
      value: false
    use_syslog:
      schema: bool
      value: false
    log_facility:
      schema: str
      value: 'LOG_USER'
    install_utilities:
      schema: bool
      value: true
    notification_driver:
      schema: [str]
      value: []
    notification_topics:
      schema: str
      value: 'notifications'
    notify_api_faults:
      schema: bool
      value: false
    notify_on_state_change:
      schema: str
      value:
    mysql_module:
      schema: str
      value:
    nova_cluster_id:
      schema: str
      value:
    sql_connection:
      schema: str
      value:
    sql_idle_timeout:
      schema: str
      value:
    logdir:
      schema: str
      value:
    os_region_name:
      schema: str
      value:

    db_user:
      schema: str!
      value: nova
    db_password:
      schema: str!
      value:
    db_name:
      schema: str!
      value:
    db_host:
      schema: str!
      value:
    db_port:
      schema: int!
      value:

    keystone_password:
      schema: str!
      value: 
    keystone_port:
      schema: int!
      value:
    keystone_host:
      schema: str!
      value:
    keystone_tenant:
      schema: str!
      value:
    keystone_user:
      schema: str!
      value:

    glance_api_servers_port:
      schema: int
      value: 9292
    glance_api_servers_host:
      schema: 'str'
      value: 'localhost'

    port:
      schema: int!
      value: 8774

    module:
      schema: {repository: str!, branch: str!}
      value: {name: 'nova', type: 'git', url: 'https://github.com/openstack/puppet-nova', ref: '5.1.0'}

    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:

tags: [resource/nova_service, resources/nova]
