handler: ansible
version: 1.0.0
actions:
  commit: commit.yaml
  run: run.yaml
  join: join.yaml
input:
    ip:
      schema: str!
      value:
    riak_self_name:
      schema: str!
      value:
    riak_hostname:
      schema: str!
      value:
    riak_name:
      schema: str!
      value: null
      computable:
        lang: jinja2
        type: full
        func: "{{riak_self_name}}@{{riak_hostname}}"
    riak_port_http:
      schema: int!
      value: 18098
    riak_port_pb:
      schema: int!
      value: 18087
    riak_port_solr:
      schema: int!
      value: 8985
    join_to:
      schema: str
      value:
    storage_backend:
      schema: str!
      value: bitcask
