handler: ansible
version: 1.0.0
input:
    volume_name:
      schema: str!
      value:
    path:
      schema: str!
      value:

    # not used, for now all VGs are file based
    type:
      schema: str!
      value: 'file'

    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:

tags: [resource/volume_group]
