handler: puppet
puppet_module: nova
version: 1.0.0
input:
    auth_host:
      schema: str
      value: 'localhost'
    auth_port:
      schema: int
      value: 35357
    auth_protocol:
      schema: str
      value: 'http'
    neutron_endpoint_host:
      schema: str
      value: 'localhost'
    neutron_endpoint_port:
      schema: int
      value: 9696
    neutron_endpoint_protocol:
      schema: str
      value: 'http'

    libvirt_vif_driver:
      schema: str
      value: 'nova.virt.libvirt.vif.LibvirtGenericVIFDriver'
    force_snat_range:
      schema: str
      value: '0.0.0.0/0'
    neutron_admin_password:
      schema: str
      value: 'neutron'
    neutron_auth_strategy:
      schema: str
      value: 'keystone'
    neutron_url_timeout:
      schema: int
      value: 30
    neutron_admin_tenant_name:
      schema: str
      value: 'services'
    neutron_default_tenant_id:
      schema: str
      value: 'default'
    neutron_region_name:
      schema: str
      value: 'RegionOne'
    neutron_admin_username:
      schema: str
      value: 'neutron'
    neutron_ovs_bridge:
      schema: str
      value: 'br-int'
    neutron_extension_sync_interval:
      schema: int
      value: 600
    neutron_ca_certificates_file:
      schema: str
      value:
    network_api_class:
      schema: str
      value: 'nova.network.neutronv2.api.API'
    security_group_api:
      schema: str
      value: 'neutron'
    firewall_driver:
      schema: str
      value: 'nova.virt.firewall.NoopFirewallDriver'
    vif_plugging_is_fatal:
      schema: bool
      value: true
    vif_plugging_timeout:
      schema: int
      value: 300
    dhcp_domain:
      schema: str
      value: 'novalocal'

    git:
      schema: {repository: str!, branch: str!}
      value: {repository: 'https://github.com/openstack/puppet-nova', branch: '5.1.0'}

    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:

tags: [resource/nova_neutron_service, resources/nova_neutron, resources/nova_compute, resources/nova]
