id: mariadb
handler: none
version: 1.0.0
actions:
input:
    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:
    name:
      schema: str
      value: a node
    location_id:
      schema: str!
      value: $uuid
