handler: ansible
version: 1.0.0
input:
    ip:
      schema: str!
      value:
    # ssh_user:
    #   schema: str!
    #   value: []
    # ssh_key:
    #   schema: str!
    #   value: []

    config_dir:
      schema: {src: str!, dst: str!, mode: str}
      value: {src: /etc/solar/glance, dst: /etc/glance, mode: rw}
    api_port:
      schema: int!
      value: 9292
    registry_port:
      schema: int!
      value: 9191
    keystone_ip:
      schema: str!
      value:
    keystone_port:
      schema: int!
      value: 5000
    keystone_admin_user:
      schema: str!
      value: glance_admin
    keystone_admin_password:
      schema: str!
      value: password1234
    keystone_admin_port:
      schema: int!
      value:
    keystone_admin_tenant:
      schema: str!
      value: service_admins
    mysql_ip:
      schema: str!
      value:
    mysql_db:
      schema: str!
      value:
    mysql_user:
      schema: str!
      value:
    mysql_password:
      schema: str!
      value:
