handler: ansible
version: 1.0.0
actions:
    run: run.yaml
    update: run.yaml
input:
    image: 
      schema: str!
      value: mariadb
    root_user:
      schema: str!
      value: root
    root_password:
      schema: str!
      value: mariadb
    port:
      schema: int!
      value: 3306
    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:

tags: [resource/mariadb_service, resources/mariadb]
