handler: ansible
input:
  solar_agent_user:
    schema: str!
    value:
  solar_agent_password:
    schema: str!
    value:
  # solar_agent_transport_class:
  #   schema: str!
  #   value: 
  solar_agent_port:
    schema: int!
    value: 5555
  name:
    schema: str!
    value: solar_agent
  location_id:
    schema: str
    value:
    reverse: True
    is_own: False
  transports_id:
    schema: str
    is_emit: False
