handler: ansible
version: 1.0.0
input:
    user_name:
      schema: str!
      value: openstack
    password:
      schema: str!
      value: openstack_password
    vhost_name:
      schema: str!
      value:
    tags:
      schema: str
      value: 'management'
    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:

tags: [resources/rabbitmq, resource/rabbitmq_user]
