id: rabbitmq_vhost
handler: ansible
version: 1.0.0
input:
    vhost_name:
      schema: str!
      value: openstack
    ip:
      schema: str!
      value:
    # ssh_key:
    #   schema: str!
    #   value:
    # ssh_user:
    #   schema: str!
    #   value:

tags: [resources/rabbitmq, resource/rabbitmq_vhost]
